-
  name: 'PaperTiger Submit'
  uriPattern: 'papertiger/submit'
  defaults:
    '@package': 'Sitegeist.PaperTiger.CPX'
    '@subpackage': ''
    '@controller': 'Form'
    '@action': 'submit'
    '@format': 'json'
  httpMethods: ['POST']
