-
  name: 'PaperTiger FormData Json'
  uriPattern: 'papertiger/json'
  defaults:
    '@package': 'Sitegeist.PaperTiger.CPX'
    '@subpackage': ''
    '@controller': 'FormSubmissionJson'
    '@action': 'json'
    '@format': 'json'
  httpMethods: ['GET', 'POST']
