Sitegeist:
  PaperTiger:
    CPX: { }
  SchemeOnYou:
    documents:
      papertiger:
        name: papertiger
        classNames:
          - 'Sitegeist\PaperTiger\CPX\Controller\FormSubmissionController'

Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.PaperTiger.CPX':
          position: 'before Neos.Neos'
  Neos:
    nodeTypes:
      groups:
        'form.elements':
          label: 'Sitegeist.PaperTiger.CPX:Main:nodeTypes.groups.form.elements'
          collapsed: false
        'form.special':
          label: 'Sitegeist.PaperTiger.CPX:Main:nodeTypes.groups.form.special'
          collapsed: false

    userInterface:
      translation:
        autoInclude:
          Sitegeist.PaperTiger.CPX:
            - Main
            - 'NodeTypes/*'

    Ui:
      resources:
        javascript:
          '@sitegeist/papertiger-editors':
            resource: 'resource://Sitegeist.PaperTiger.CPX/Public/Neos.Ui/Plugin.js'
